# This is a basic workflow to help you get started with Actions

name: OWASP ZAP DAST Scanning

on:
  push:
    branches: [ main ]

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: owasp/zap2docker-stable:latest
        id: build-zap-image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          push: true
          tags: |
            owasp/zaproxy:latest

      - name: Run OWASP ZAP Docker Container
        id: run-zap-container
        uses: docker/run-action@v2
        with:
          image: ${{ steps.build-zap-image.outputs.docker-registry }}owasp/zap2docker-stable:latest
          ports: |
            8080:8080

      - name: Run OWASP ZAP DAST Scan
        id: zap-scan
        run: |
          curl -X POST http://localhost:8080/JSON/spider/action/scan/?url=${{ github.event.repository.url }} | jq .scanId

      - name: Retrieve OWASP ZAP Scan Results
        id: get-zap-results
        run: |
          curl http://localhost:8080/JSON/reporting/view/results/?scanId=${{ steps.zap-scan.outputs.scanId }} | jq .alerts

      - name: Fail if OWASP ZAP Scan Finds Vulnerabilities
        if: ${{ steps.get-zap-results.outputs.get-zap-results.length > 0 }}
        id: fail-on-vulnerabilities
        steps:
          - name: Fail
            run: echo "OWASP ZAP DAST Scan found vulnerabilities. Please review the scan results."
            exit-status: 1
